# Generated by Django 5.1.7 on 2025-03-27 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.book')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.child')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
