# Generated by Django 5.1.7 on 2025-04-21 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_userprofile_invite_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.child'),
        ),
    ]
