# Generated by Django 5.1.7 on 2025-03-30 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_readhistory_options_alter_readhistory_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='readhistory',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='readhistory',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
