# Generated by Django 5.1.6 on 2025-03-10 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_favoritebook_remove_book_published_date_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-03-10 00:00:00'),
            preserve_default=False,
        ),
    ]
