# Generated by Django 5.1.6 on 2025-03-11 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_book_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavoriteBook',
        ),
    ]
