# Generated by Django 5.1.7 on 2025-03-17 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_child_book_child'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=20250101),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='child',
            name='name',
            field=models.CharField(max_length=50, verbose_name='子どもの名前'),
        ),
    ]
