# Generated by Django 5.1.7 on 2025-03-17 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_child_created_at_alter_child_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
