# Generated by Django 5.1.7 on 2025-03-19 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_child_created_at_alter_child_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='child',
        ),
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memos', to='app.book')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memos', to='app.child')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='child',
            field=models.ManyToManyField(blank=True, related_name='books', to='app.child'),
        ),
    ]
